# EFAK AI Application Configuration
spring:
  # Application Configuration
  application:
    name: efak-ai
  
  # Main Configuration
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  
  # Web Configuration
  web:
    resources:
      static-locations: classpath:/statics/
  
  # AOP Configuration
  aop:
    proxy-target-class: true
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/efak_ai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 3000
      connection-timeout: 10000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
  
  # Jackson Configuration
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 3000ms

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    path: /error
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Logging Configuration
logging:
  level:
    org.apache.ibatis: WARN
    org.springframework.jdbc.datasource.DataSourceTransactionManager: WARN
    com.zaxxer.hikari.pool.ProxyConnection: ERROR
    # Kafka日志配置 - 禁止AbstractConfig的日志输出
    org.apache.kafka.common.config.AbstractConfig: ERROR
    org.apache.kafka: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN
    # 分布式任务调度日志配置
    org.kafka.eagle.web.scheduler: DEBUG
    org.kafka.eagle.web.service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{nodeId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{nodeId}] %logger{36} - %msg%n"

# EFAK Distributed Task Configuration
efak:
  distributed:
    task:
      # 节点离线超时时间（秒）
      offline-timeout: 120

      # 分片结果等待时间（秒）
      shard-result-wait-time: 30

      # 分片结果过期时间（分钟）
      shard-result-expire-minutes: 10

  # 数据保留时间（天）
  data-retention-days: 7